name: Answer on the third comment of an issue
run-name: ${{ github.actor }}  is testing out GitHub Actions 🚀
on: 
  issue_comment:
    types: [created]
jobs:
  issue_commented:
    name: Issue Comment
    if: ${{ !github.event.issue.pull_request }}
    uses: peter-evans/create-or-update-comment/.github/workflows/create-or-update-comment.yml@v2
    with:
      issue-number: ${{ github.event.issue.number }}
      body: |
        This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
        
        [1]: https://github.com/peter-evans/create-or-update-comment
      reactions: +1
